export const ADD_RECORD = 'ADD_RECORD';
export const REQUEST_RECORDS = 'REQUEST_RECORDS';
export const RECEIVE_RECORDS = 'RECEIVE_RECORDS';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const DELETE_RECORD = 'DELETE_RECORD';
